name: Perf Changelog
on:
  # Disabled: not needed for app chain
  # pull_request:
  #   types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  # Enforces the update of a changelog file on every pull request
  # We only want this for perf-related changes for now, so we add a few labels
  # for which the check is skipped
  changelog:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'performance') && !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3
