"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { deploymentsApi } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { Deployment } from "@/lib/types";

function generateTomlConfig(deployment: Deployment): string {
  return `# ethrex L2 Configuration
# Generated by Guest Program Store
# Deployment: ${deployment.name}

[network]
chain_id = ${deployment.chain_id || 0}
l1_rpc_url = "${deployment.rpc_url || "http://localhost:8545"}"

[guest_program]
program_id = "${deployment.program_slug || deployment.program_id}"
program_name = "${deployment.program_name || ""}"
${deployment.category ? `category = "${deployment.category}"` : ""}

[prover]
# Available backends: sp1, risc0
backend = "sp1"
# Set to true to enable proof generation
enabled = true

[sequencer]
# Block time in seconds
block_time = 2
# Maximum gas per block
max_block_gas = 30000000
`;
}

export default function DeploymentDetailPage() {
  const params = useParams();
  const router = useRouter();
  const { user } = useAuth();
  const [deployment, setDeployment] = useState<Deployment | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [deleting, setDeleting] = useState(false);

  // Edit mode
  const [editing, setEditing] = useState(false);
  const [editName, setEditName] = useState("");
  const [editChainId, setEditChainId] = useState("");
  const [editRpcUrl, setEditRpcUrl] = useState("");
  const [saving, setSaving] = useState(false);

  // Config export
  const [showConfig, setShowConfig] = useState(false);

  useEffect(() => {
    if (!params.id || !user) return;
    deploymentsApi
      .get(params.id as string)
      .then((d) => {
        setDeployment(d);
        setEditName(d.name);
        setEditChainId(d.chain_id?.toString() || "");
        setEditRpcUrl(d.rpc_url || "");
      })
      .catch((err) => setError(err instanceof Error ? err.message : "Failed to load"))
      .finally(() => setLoading(false));
  }, [params.id, user]);

  const handleSave = async () => {
    if (!deployment || !editName.trim()) return;
    setSaving(true);
    try {
      const updated = await deploymentsApi.update(deployment.id, {
        name: editName.trim(),
        chain_id: editChainId ? parseInt(editChainId) : null,
        rpc_url: editRpcUrl || null,
      });
      setDeployment(updated);
      setEditing(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save");
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!confirm("Remove this deployment?")) return;
    setDeleting(true);
    try {
      await deploymentsApi.remove(deployment!.id);
      router.push("/deployments");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete");
      setDeleting(false);
    }
  };

  const handleDownloadConfig = () => {
    if (!deployment) return;
    const toml = generateTomlConfig(deployment);
    const blob = new Blob([toml], { type: "application/toml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${deployment.name.toLowerCase().replace(/\s+/g, "-")}-l2-config.toml`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!user) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-16 text-center">
        <Link href="/login" className="text-blue-600 hover:underline">Login required</Link>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" />
      </div>
    );
  }

  if (error || !deployment) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-16 text-center">
        <h1 className="text-xl font-bold text-red-600 mb-4">Deployment Not Found</h1>
        <p className="text-gray-600 mb-4">{error}</p>
        <Link href="/deployments" className="text-blue-600 hover:underline">
          Back to Deployments
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <Link href="/deployments" className="text-blue-600 hover:underline text-sm mb-4 inline-block">
        &larr; Back to Deployments
      </Link>

      <div className="bg-white rounded-xl shadow-sm border p-8">
        <div className="flex items-start justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold">{deployment.name}</h1>
            <p className="text-gray-500 mt-1">
              Program: {deployment.program_name || deployment.program_id}
              {deployment.category && (
                <span className="ml-2 px-2 py-0.5 bg-gray-100 rounded text-xs">
                  {deployment.category}
                </span>
              )}
            </p>
          </div>
          <span
            className={`px-3 py-1 rounded-full text-sm font-medium ${
              deployment.status === "configured"
                ? "bg-yellow-100 text-yellow-700"
                : deployment.status === "active"
                ? "bg-green-100 text-green-700"
                : "bg-gray-100 text-gray-600"
            }`}
          >
            {deployment.status}
          </span>
        </div>

        {/* Configuration Section */}
        <div className="border-t pt-6 mb-6">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-lg font-semibold">Configuration</h2>
            {!editing && (
              <button
                onClick={() => setEditing(true)}
                className="text-blue-600 text-sm hover:underline"
              >
                Edit
              </button>
            )}
          </div>

          {editing ? (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Deployment Name
                </label>
                <input
                  type="text"
                  value={editName}
                  onChange={(e) => setEditName(e.target.value)}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Chain ID
                </label>
                <input
                  type="number"
                  value={editChainId}
                  onChange={(e) => setEditChainId(e.target.value)}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="e.g. 12345"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  L1 RPC URL
                </label>
                <input
                  type="text"
                  value={editRpcUrl}
                  onChange={(e) => setEditRpcUrl(e.target.value)}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="https://..."
                />
              </div>
              <div className="flex gap-2">
                <button
                  onClick={handleSave}
                  disabled={saving}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 disabled:opacity-50"
                >
                  {saving ? "Saving..." : "Save Changes"}
                </button>
                <button
                  onClick={() => {
                    setEditing(false);
                    setEditName(deployment.name);
                    setEditChainId(deployment.chain_id?.toString() || "");
                    setEditRpcUrl(deployment.rpc_url || "");
                  }}
                  className="px-4 py-2 border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <dl className="space-y-3 text-sm">
              <div className="flex justify-between">
                <dt className="text-gray-500">Chain ID</dt>
                <dd className="font-medium">{deployment.chain_id || "Not set"}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-gray-500">L1 RPC URL</dt>
                <dd className="font-medium font-mono text-xs">
                  {deployment.rpc_url || "Not set"}
                </dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-gray-500">Created</dt>
                <dd className="font-medium">
                  {new Date(deployment.created_at).toLocaleString()}
                </dd>
              </div>
            </dl>
          )}
        </div>

        {/* L2 Config Export */}
        <div className="border-t pt-6 mb-6">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-lg font-semibold">L2 Node Configuration</h2>
            <div className="flex gap-2">
              <button
                onClick={() => setShowConfig(!showConfig)}
                className="text-blue-600 text-sm hover:underline"
              >
                {showConfig ? "Hide" : "Preview"}
              </button>
              <button
                onClick={handleDownloadConfig}
                className="px-3 py-1.5 bg-gray-900 text-white rounded-lg text-sm hover:bg-gray-800"
              >
                Download .toml
              </button>
            </div>
          </div>
          <p className="text-sm text-gray-500 mb-3">
            Generate a TOML configuration file to run an ethrex L2 node with this guest program.
          </p>
          {showConfig && (
            <pre className="bg-gray-900 text-gray-100 rounded-lg p-4 text-xs overflow-x-auto">
              {generateTomlConfig(deployment)}
            </pre>
          )}
        </div>

        {/* Actions */}
        <div className="border-t pt-6 flex gap-3">
          {deployment.status === "configured" && (
            <button
              onClick={async () => {
                try {
                  const updated = await deploymentsApi.activate(deployment.id);
                  setDeployment(updated);
                } catch (err) {
                  setError(err instanceof Error ? err.message : "Failed to activate");
                }
              }}
              className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
            >
              Activate Deployment
            </button>
          )}
          <button
            onClick={handleDelete}
            disabled={deleting}
            className="px-4 py-2 border border-red-300 text-red-600 rounded-lg hover:bg-red-50 disabled:opacity-50"
          >
            {deleting ? "Removing..." : "Remove Deployment"}
          </button>
        </div>
      </div>
    </div>
  );
}
