"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { deploymentsApi } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { Deployment } from "@/lib/types";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5001";

function parseConfig(deployment: Deployment): { mode: string; l1Image: string } {
  try {
    const parsed = deployment.config ? JSON.parse(deployment.config) : {};
    return {
      mode: parsed.mode || "local",
      l1Image: parsed.l1Image || "ethrex",
    };
  } catch {
    return { mode: "local", l1Image: "ethrex" };
  }
}

function generateTomlConfig(deployment: Deployment): string {
  const slug = deployment.program_slug || deployment.program_id;

  return `# Guest Program Registry Configuration
# Generated by GP Store for: ${deployment.name}
#
# Place this file at crates/l2/programs.toml
# or pass via: --programs-config /path/to/programs.toml

# The default guest program for this L2
default_program = "${slug}"

# Programs to register in the prover
enabled_programs = ["${slug}"]
`;
}

function generateDockerCompose(deployment: Deployment): string {
  const slug = deployment.program_slug || deployment.program_id;
  const { mode } = parseConfig(deployment);

  if (mode === "local") {
    return `# ethrex L2 — Local mode (L1 + L2)
# Clone: git clone https://github.com/tokamak-network/ethrex.git && cd ethrex
# Run:   ETHREX_GUEST_PROGRAM_ID=${slug} make -C crates/l2 init-guest-program PROGRAM=${slug}
# Stop:  make -C crates/l2 down-guest-program
#
# Or use docker compose directly:
#   cd crates/l2
#   ETHREX_GUEST_PROGRAM_ID=${slug} DOCKER_ETHREX_WORKDIR=/usr/local/bin \\
#     docker compose -f docker-compose.yaml -f docker-compose-guest-program.overrides.yaml up -d --build
#
# Endpoints:
#   L1 RPC: http://localhost:8545
#   L2 RPC: http://localhost:1729
`;
  }

  return `# ethrex L2 — Production mode
# Clone: git clone https://github.com/tokamak-network/ethrex.git && cd ethrex
# Run:   ETHREX_GUEST_PROGRAM_ID=${slug} make -C crates/l2 init-guest-program PROGRAM=${slug}
# Stop:  make -C crates/l2 down-guest-program
#
# Endpoints:
#   L2 RPC: http://localhost:1729
`;
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function DeploymentDetailPage() {
  const params = useParams();
  const router = useRouter();
  const { user } = useAuth();
  const [deployment, setDeployment] = useState<Deployment | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [deleting, setDeleting] = useState(false);

  // Edit mode
  const [editing, setEditing] = useState(false);
  const [editName, setEditName] = useState("");
  const [editChainId, setEditChainId] = useState("");
  const [editRpcUrl, setEditRpcUrl] = useState("");
  const [saving, setSaving] = useState(false);

  // Config export
  const [showConfig, setShowConfig] = useState(false);

  useEffect(() => {
    if (!params.id || !user) return;
    deploymentsApi
      .get(params.id as string)
      .then((d) => {
        setDeployment(d);
        setEditName(d.name);
        setEditChainId(d.chain_id?.toString() || "");
        setEditRpcUrl(d.rpc_url || "");
      })
      .catch((err) => setError(err instanceof Error ? err.message : "Failed to load"))
      .finally(() => setLoading(false));
  }, [params.id, user]);

  const handleSave = async () => {
    if (!deployment || !editName.trim()) return;
    setSaving(true);
    try {
      const updated = await deploymentsApi.update(deployment.id, {
        name: editName.trim(),
        chain_id: editChainId ? parseInt(editChainId) : null,
        rpc_url: editRpcUrl || null,
      });
      setDeployment(updated);
      setEditing(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save");
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!confirm("Remove this L2?")) return;
    setDeleting(true);
    try {
      await deploymentsApi.remove(deployment!.id);
      router.push("/deployments");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete");
      setDeleting(false);
    }
  };

  const handleDownloadToml = () => {
    if (!deployment) return;
    const toml = generateTomlConfig(deployment);
    downloadFile(toml, "programs.toml", "application/toml");
  };

  const handleDownloadGuide = () => {
    if (!deployment) return;
    const guide = generateDockerCompose(deployment);
    downloadFile(guide, "README.txt", "text/plain");
  };

  const handleDownloadAll = () => {
    if (!deployment) return;
    handleDownloadToml();
    setTimeout(() => handleDownloadGuide(), 100);
  };

  if (!user) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-16 text-center">
        <Link href="/login" className="text-blue-600 hover:underline">Login required</Link>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" />
      </div>
    );
  }

  if (error || !deployment) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-16 text-center">
        <h1 className="text-xl font-bold text-red-600 mb-4">L2 Not Found</h1>
        <p className="text-gray-600 mb-4">{error}</p>
        <Link href="/deployments" className="text-blue-600 hover:underline">
          Back to My L2s
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <Link href="/deployments" className="text-blue-600 hover:underline text-sm mb-4 inline-block">
        &larr; Back to My L2s
      </Link>

      <div className="bg-white rounded-xl shadow-sm border p-8">
        <div className="flex items-start justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold">{deployment.name}</h1>
            <p className="text-gray-500 mt-1">
              Program: {deployment.program_name || deployment.program_id}
              {deployment.category && (
                <span className="ml-2 px-2 py-0.5 bg-gray-100 rounded text-xs">
                  {deployment.category}
                </span>
              )}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <span
              className={`px-3 py-1 rounded-full text-sm font-medium ${
                parseConfig(deployment).mode === "local"
                  ? "bg-purple-100 text-purple-700"
                  : "bg-indigo-100 text-indigo-700"
              }`}
            >
              {parseConfig(deployment).mode === "local" ? "Local" : "Production"}
            </span>
            <span
              className={`px-3 py-1 rounded-full text-sm font-medium ${
                deployment.status === "configured"
                  ? "bg-yellow-100 text-yellow-700"
                  : deployment.status === "active"
                  ? "bg-green-100 text-green-700"
                  : "bg-gray-100 text-gray-600"
              }`}
            >
              {deployment.status}
            </span>
          </div>
        </div>

        {/* Configuration Section */}
        <div className="border-t pt-6 mb-6">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-lg font-semibold">Configuration</h2>
            {!editing && (
              <button
                onClick={() => setEditing(true)}
                className="text-blue-600 text-sm hover:underline"
              >
                Edit
              </button>
            )}
          </div>

          {editing ? (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  L2 Name
                </label>
                <input
                  type="text"
                  value={editName}
                  onChange={(e) => setEditName(e.target.value)}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Chain ID
                </label>
                <input
                  type="number"
                  value={editChainId}
                  onChange={(e) => setEditChainId(e.target.value)}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="10000~99999 recommended"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  L1 RPC URL
                </label>
                <input
                  type="text"
                  value={editRpcUrl}
                  onChange={(e) => setEditRpcUrl(e.target.value)}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="https://..."
                />
              </div>
              <div className="flex gap-2">
                <button
                  onClick={handleSave}
                  disabled={saving}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 disabled:opacity-50"
                >
                  {saving ? "Saving..." : "Save Changes"}
                </button>
                <button
                  onClick={() => {
                    setEditing(false);
                    setEditName(deployment.name);
                    setEditChainId(deployment.chain_id?.toString() || "");
                    setEditRpcUrl(deployment.rpc_url || "");
                  }}
                  className="px-4 py-2 border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <dl className="space-y-3 text-sm">
              <div className="flex justify-between">
                <dt className="text-gray-500">Chain ID</dt>
                <dd className="font-medium">{deployment.chain_id || "Not set"}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-gray-500">L1 RPC URL</dt>
                <dd className="font-medium font-mono text-xs">
                  {deployment.rpc_url || "Not set"}
                </dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-gray-500">Created</dt>
                <dd className="font-medium">
                  {new Date(deployment.created_at).toLocaleString()}
                </dd>
              </div>
            </dl>
          )}
        </div>

        {/* L2 Config Export */}
        <div className="border-t pt-6 mb-6">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-lg font-semibold">L2 Node Configuration</h2>
            <div className="flex gap-2">
              <button
                onClick={() => setShowConfig(!showConfig)}
                className="text-blue-600 text-sm hover:underline"
              >
                {showConfig ? "Hide" : "Preview"}
              </button>
              <button
                onClick={handleDownloadToml}
                className="px-3 py-1.5 border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Download programs.toml
              </button>
              <button
                onClick={handleDownloadGuide}
                className="px-3 py-1.5 border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
              >
                Download README
              </button>
              <button
                onClick={handleDownloadAll}
                className="px-3 py-1.5 bg-gray-900 text-white rounded-lg text-sm hover:bg-gray-800"
              >
                Download All
              </button>
            </div>
          </div>
          <p className="text-sm text-gray-500 mb-3">
            Download configuration files to run an ethrex L2 node with this guest program.
          </p>
          {showConfig && (
            <div className="space-y-4">
              <div>
                <p className="text-xs font-medium text-gray-500 mb-1">programs.toml</p>
                <pre className="bg-gray-900 text-gray-100 rounded-lg p-4 text-xs overflow-x-auto">
                  {generateTomlConfig(deployment)}
                </pre>
              </div>
              <div>
                <p className="text-xs font-medium text-gray-500 mb-1">Quick Start Guide</p>
                <pre className="bg-gray-900 text-gray-100 rounded-lg p-4 text-xs overflow-x-auto">
                  {generateDockerCompose(deployment)}
                </pre>
              </div>
            </div>
          )}
        </div>

        {/* Quick Start Guide */}
        <div className="border-t pt-6 mb-6">
          <h2 className="text-lg font-semibold mb-3">Quick Start</h2>
          <div className="bg-gray-50 rounded-lg p-4 text-sm space-y-3">
            <div>
              <p className="font-medium text-gray-700 mb-1">1. Clone ethrex</p>
              <pre className="bg-gray-900 text-gray-100 rounded p-2 text-xs">
{`git clone https://github.com/tokamak-network/ethrex.git
cd ethrex`}
              </pre>
            </div>
            <div>
              <p className="font-medium text-gray-700 mb-1">2. Run with guest program</p>
              <pre className="bg-gray-900 text-gray-100 rounded p-2 text-xs">
{`make -C crates/l2 init-guest-program PROGRAM=${deployment.program_slug || deployment.program_id}`}
              </pre>
            </div>
            <div>
              <p className="font-medium text-gray-700 mb-1">3. Endpoints</p>
              <div className="text-gray-500 space-y-1">
                <p>L1 RPC: <code className="bg-gray-200 px-1 rounded text-xs">http://localhost:8545</code></p>
                <p>L2 RPC: <code className="bg-gray-200 px-1 rounded text-xs">http://localhost:1729</code></p>
              </div>
            </div>
            <div>
              <p className="font-medium text-gray-700 mb-1">4. Stop</p>
              <pre className="bg-gray-900 text-gray-100 rounded p-2 text-xs">
{`make -C crates/l2 down-guest-program`}
              </pre>
            </div>
            <div className="pt-2 border-t">
              <Link href="/guide" className="text-blue-600 hover:underline text-sm font-medium">
                Need help? View setup guide &rarr;
              </Link>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="border-t pt-6">
          <button
            onClick={handleDelete}
            disabled={deleting}
            className="px-4 py-2 border border-red-300 text-red-600 rounded-lg hover:bg-red-50 disabled:opacity-50"
          >
            {deleting ? "Removing..." : "Remove L2"}
          </button>
        </div>
      </div>
    </div>
  );
}
